#!/usr/bin/env node
/* =============================================================
 * Mugznlugz Portal — build.js
 * -------------------------------------------------------------
 * Reads `.env` and writes `config.js`.
 *
 * Usage:
 *   node build.js            # reads .env in project root
 *   node build.js --check    # exits 1 if .env has placeholder values
 *
 * Zero dependencies — runs on any Node 14+.
 * ============================================================= */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = __dirname;
const ENV_FILE    = path.join(ROOT, '.env');
const OUT_FILE    = path.join(ROOT, 'config.js');
const CHECK_MODE  = process.argv.includes('--check');

/* ---------- minimal .env parser (no dependency) ---------- */
function parseEnv(text) {
  const env = {};
  text.split(/\r?\n/).forEach((raw) => {
    const line = raw.trim();
    if (!line || line.startsWith('#')) return;
    const eq = line.indexOf('=');
    if (eq === -1) return;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();

    // strip surrounding quotes if present
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  });
  return env;
}

/* ---------- read sources ---------- */
let envText = '';
try {
  envText = fs.readFileSync(ENV_FILE, 'utf8');
} catch (err) {
  // fall back to .env.example so the site is buildable on a fresh clone
  const example = path.join(ROOT, '.env.example');
  if (fs.existsSync(example)) {
    console.warn('[build] .env not found — using .env.example defaults.');
    envText = fs.readFileSync(example, 'utf8');
  } else {
    console.error('[build] No .env or .env.example found. Aborting.');
    process.exit(1);
  }
}

/* Let process.env override file values (useful in CI) */
const fileEnv = parseEnv(envText);
const env = { ...fileEnv };
for (const k of Object.keys(fileEnv)) {
  if (typeof process.env[k] === 'string' && process.env[k] !== '') {
    env[k] = process.env[k];
  }
}

/* ---------- coercion helpers ---------- */
const str  = (k, d = '') => (env[k] ?? d).toString();
const bool = (k, d = false) => {
  const v = (env[k] ?? '').toString().toLowerCase();
  if (['1', 'true', 'yes', 'on'].includes(v))  return true;
  if (['0', 'false', 'no', 'off'].includes(v)) return false;
  return d;
};
const num = (k, d) => {
  const n = Number(env[k]);
  return Number.isFinite(n) ? n : d;
};
const list = (k) => {
  const raw = (env[k] ?? '').trim();
  if (!raw) return [];
  return raw.split(',').map(s => s.trim()).filter(Boolean);
};

/* ---------- shape config ---------- */
const config = {
  SITE_URL:             str('SITE_URL', 'https://www.mugznlugz.com'),
  FORCE_EMBED_FALLBACK: bool('FORCE_EMBED_FALLBACK', false),
  EMBED_TIMEOUT_MS:     num('EMBED_TIMEOUT_MS', 3500),
  EMBED_PREVIEW_URL:    str('EMBED_PREVIEW_URL', ''),

  CLIENT_ID:            str('CLIENT_ID'),
  API_KEY:              str('API_KEY'),
  FOLDER_ID:            str('FOLDER_ID'),
  SCOPES:               str('SCOPES', 'https://www.googleapis.com/auth/drive.readonly'),

  DEMO_IMAGES:          list('DEMO_IMAGES'),
};

/* ---------- --check mode ---------- */
if (CHECK_MODE) {
  const missing = [];
  if (config.CLIENT_ID.startsWith('YOUR_')) missing.push('CLIENT_ID');
  if (config.API_KEY.startsWith('YOUR_'))   missing.push('API_KEY');
  if (config.FOLDER_ID.startsWith('YOUR_')) missing.push('FOLDER_ID');

  if (missing.length) {
    console.error(`[build --check] Missing or placeholder values: ${missing.join(', ')}`);
    process.exit(1);
  }
  console.log('[build --check] .env looks good.');
  process.exit(0);
}

/* ---------- write config.js ---------- */
const header = `/* =============================================================
 * Mugznlugz Portal — config.js
 * -------------------------------------------------------------
 * AUTO-GENERATED by build.js from .env — do not edit by hand.
 * Edit .env instead, then run:  node build.js
 * Generated: ${new Date().toISOString()}
 * ============================================================= */\n\n`;

const body = `window.MZL_CONFIG = ${JSON.stringify(config, null, 2)};\n`;

fs.writeFileSync(OUT_FILE, header + body, 'utf8');
console.log(`[build] Wrote ${path.relative(ROOT, OUT_FILE)} (${Object.keys(config).length} keys).`);
