/* =============================================================
 * Mugznlugz Portal — config.js
 * -------------------------------------------------------------
 * AUTO-GENERATED by build.js from .env — do not edit by hand.
 * Edit .env instead, then run:  node build.js
 * Generated: 2026-04-20T17:15:50.196Z
 * ============================================================= */

window.MZL_CONFIG = {
  "SITE_URL": "https://www.mugznlugz.com",
  "FORCE_EMBED_FALLBACK": false,
  "EMBED_TIMEOUT_MS": 3500,
  "EMBED_PREVIEW_URL": "https://s.wordpress.com/mshots/v1/{url}?w=1280&h=800",
  "CLIENT_ID": "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com",
  "API_KEY": "YOUR_GOOGLE_API_KEY",
  "FOLDER_ID": "YOUR_DRIVE_FOLDER_ID",
  "SCOPES": "https://www.googleapis.com/auth/drive.readonly",
  "DEMO_IMAGES": [
    "https://images.unsplash.com/photo-1517059224940-d4af9eec41b7?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1542219550-37153d387c27?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&w=1200&q=80"
  ]
};
